name: bhf_player
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.5.0
  crypto: ^3.0.6
  encrypt: ^5.0.3
  file_picker: ^10.3.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  # jailbreak_root_detection: ^1.1.6
  rename: ^3.1.0
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.6
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  get_it: ^8.0.3
  media_kit:
    git:
      url: https://github.com/Zain-net/media-kit-pro.git
      ref: main   
      path: media_kit    

  media_kit_video:
    git:
      url: https://github.com/Zain-net/media-kit-pro.git
      ref: main
      path: media_kit_video 

  media_kit_libs_video: ^1.0.6 # Native video dependencies.
  flashy_flushbar: ^1.4.0
  sqflite: ^2.4.2
  svg_flutter: ^0.0.1
  pool: ^1.5.1
  equatable: ^2.0.7
  window_manager: ^0.5.1
  screen_brightness: ^2.1.6
  volume_controller: ^3.4.0
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/icons/

  fonts:
  - family: Space Grotesk
    fonts:
    - asset: assets/fonts/SpaceGrotesk-Light.ttf
      weight: 300
    - asset: assets/fonts/SpaceGrotesk-Bold.ttf
      weight: 700
